name: CI

on: [push]


    
jobs:
  build:

      
    runs-on: ubuntu-latest
    strategy:
      matrix:
        luaVersion: ["5.1.5", "5.2.4"]

    steps:

    - uses: actions/checkout@v1
    - uses: leafo/gh-actions-lua@v5
      with:
        luaVersion: ${{ matrix.luaVersion }}
    - uses: leafo/gh-actions-luarocks@v2

    - name: build
      run: |
        luarocks install busted
        luarocks install luacheck
        luarocks make
    
    - name: check
      run: |
        luacheck lorem-0.1-0.rockspec
        
    - name: test
      run: |
        busted 
